### ISSUE TITLE
Metadata for parent of books not visible

### ISSUE THREAD

**Issue by lucasvanschaik** [mjordan/islandora_compound_parent_metadata#1]
We use the compound module to group a book series. Unfortunately the islandora_compound_parent_metadata module does not work when displaying a book inside a compound. Probably, this has to do with the markup that is changed as $rendered[NULL]['#markup'] but the book markup is located at $rendered['islandora_book']['#markup']. Is it possible to modify this module so books (and all other items) will work as well?

**Comment by mjordan** [comment]
Hi @lucasvanschaik, Islandora Simple Map had a [similar issue](https://github.com/mjordan/islandora_simple_map/issues/8). I'll fix this within the next week or so; when I have a fix, would you help test?

**Comment by lucasvanschaik** [comment]
Hi Mark Jordan,

Thanks for the quick reply.
The solution looks similar indeed. Something like islandora_simple_map_get_rendered_member
Of course I want to help with testing. Let me know when the fix is ready, and I'll be happy to test.
The Islandora Simple Map  looks good too, we might use that later on.

Thanks,
Lucas


On 08 Feb 2017, at 16:26, Mark Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @lucasvanschaik<https://github.com/lucasvanschaik>, Islandora Simple Map had a similar issue<https://github.com/mjordan/islandora_simple_map/issues/8>. I'll fix this within the next week or so; when I have a fix, would you help test?

**Comment by lucasvanschaik** [comment]
Hi Mark Jordan,

Hope I am not intruding, but I wanted to let you know that I did some work myself based on your module islandora_compound_parent_metadata and the module islandora_blocks by echidnacorp. Combining those two I've made a module that can display the parent metadata of a compound as a block, so it can be placed anywhere on a page.
It is located at: https://github.com/LeidenUniversityLibrary/islandora_compound_parent_metadata_block
It is not quite finished, but I like to know what you think.

regards,
Lucas

Lucas van Schaik
Developer/Consultant
Leiden University Library




On 08 Feb 2017, at 17:07, Schaik, L.B. van <L.B.van.Schaik@Library.LeidenUniv.NL<mailto:L.B.van.Schaik@library.leidenuniv.nl>> wrote:

Hi Mark Jordan,

Thanks for the quick reply.
The solution looks similar indeed. Something like islandora_simple_map_get_rendered_member
Of course I want to help with testing. Let me know when the fix is ready, and I'll be happy to test.
The Islandora Simple Map  looks good too, we might use that later on.

Thanks,
Lucas


On 08 Feb 2017, at 16:26, Mark Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @lucasvanschaik<https://github.com/lucasvanschaik>, Islandora Simple Map had a similar issue<https://github.com/mjordan/islandora_simple_map/issues/8>. I'll fix this within the next week or so; when I have a fix, would you help test?

**Comment by mjordan** [comment]
@lucasvanschaik I'm extremely sorry that I never responded to your issue. I'm closing this, not only because you created your own solution, but also because the fix for #3 solves this issue too. Again, I apologize for dropping the ball on this one.

**Comment by mjordan** [comment]
Resolved with cb7329d112b5b2892717c81f280a59872f9271fc.

**Comment by lucasvanschaik** [comment]
@mjordan No worries, nice that it is fixed now!
