### ISSUE TITLE
No metadata for parents of Citation objects

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_compound_parent_metadata#2]
Tried this out today on a test compound object containing two Citations and a Large Image. The Large Image got the Parent metadata block, but the Citations did not.

Does this module only work for certain CModels?

**Comment by mjordan** [comment]
@bondjimbond it's safe to say it works with the cmodels it was tested with, but citation would not have been one of them. I wrote this module before I created a Context reaction to do the same thing. AFAIK it was only ever used by one site (not SFU).

If this solves your problem before the Compound SP stuff gets worked out, we can always enhance it

**Comment by mjordan** [comment]
@bondjimbond fix in issue-3 branch also solves this one.

**Comment by mjordan** [comment]
And solves #1.

**Comment by mjordan** [comment]
Resolved with cb7329d112b5b2892717c81f280a59872f9271fc.

**Comment by mjordan** [comment]
Resolved with cb7329d112b5b2892717c81f280a59872f9271fc.
